// WHY: session id, oldpwd dedup, and prompt-wrapping mirror zoxide's pwsh init.
const TEMPLATE: &str = r#"# furet PowerShell integration, generated by `furet init pwsh`.
# Mirrors zoxide's PowerShell hook: a session-scoped id, an "oldpwd" dedup
# variable shared between the jump function and the prompt hook, and a
# prompt wrapper that preserves any prompt already defined (oh-my-posh etc).

$global:__furet_session = [guid]::NewGuid().ToString()
$global:__furet_last_pwd = (Get-Location).Path

function global:__furet_record($target, $from, $source) {
    furet add --session $global:__furet_session --source $source --from $from -- $target | Out-Null
    $global:__furet_last_pwd = $target
}

function global:__furet_hook {
    $current = (Get-Location).Path
    if ($current -ne $global:__furet_last_pwd) {
        __furet_record $current $global:__furet_last_pwd 'hook'
    }
}

if (Test-Path Function:\prompt) {
    $global:__furet_prompt_old = $function:prompt
} else {
    $global:__furet_prompt_old = $null
}

function global:prompt {
    __furet_hook
    if ($null -ne $global:__furet_prompt_old) {
        & $global:__furet_prompt_old
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($NestedPromptLevel + 1)) "
    }
}

function global:__FURET_CMD__ {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    if ([string]::IsNullOrEmpty($query)) {
        Set-Location -LiteralPath $HOME
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    if ($query -eq '.') {
        return
    }

    if ($query -match '^\.\.+$') {
        $levels = $query.Length - 1
        $target = furet up $levels
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'up'
        return
    }

    if ($query -eq '-') {
        $target = furet back --session $global:__furet_session
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'back'
        return
    }

    if (Test-Path -LiteralPath $query -PathType Container) {
        Set-Location -LiteralPath $query
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    $target = furet query -- $query
    if ($LASTEXITCODE -ne 0) {
        return
    }
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump'
}

function global:fi {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    if (Get-Command fzf -ErrorAction SilentlyContinue) {
        $initial = furet query --list --color
        $selection = $initial | fzf --disabled --ansi --bind "change:reload:furet query --list --color {q}"
        if ([string]::IsNullOrEmpty($selection)) {
            return
        }
        $target = $selection -replace "`e\[[0-9;]*m", ''
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }

    $candidates = @(furet query --list $query | Select-Object -First 9)
    if ($candidates.Count -eq 0) {
        return
    }
    Write-Host 'Choose a directory:'
    for ($i = 0; $i -lt $candidates.Count; $i++) {
        Write-Host "  $($i + 1)) $($candidates[$i])"
    }
    Write-Host 'Enter to confirm, Esc to cancel'
    $answer = Read-Host
    if ($answer -notmatch '^[1-9][0-9]*$') {
        return
    }
    $index = [int]$answer
    if ($index -lt 1 -or $index -gt $candidates.Count) {
        return
    }
    $target = $candidates[$index - 1]
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump'
}
"#;

/// Renders the PowerShell integration script for the jump function `cmd`.
pub fn script(cmd: &str) -> String {
    TEMPLATE.replace("__FURET_CMD__", cmd)
}

#[cfg(test)]
mod tests {
    use super::script;

    #[test]
    fn script_names_the_jump_function_after_cmd() {
        let rendered = script("f");
        assert!(rendered.contains("function global:f "));
    }

    #[test]
    fn script_never_bakes_in_a_session_id() {
        let rendered = script("f");
        assert!(rendered.contains("[guid]::NewGuid()"));
        assert!(!rendered.contains("00000000-0000-0000-0000-000000000000"));
    }

    #[test]
    fn script_defines_fi_and_reaches_for_fzf() {
        let rendered = script("f");
        assert!(rendered.contains("function global:fi "));
        assert!(rendered.contains("fzf"));
    }

    #[test]
    fn script_renders_the_spec_section_9_menu_wording_for_the_no_fzf_branch() {
        let rendered = script("f");
        assert!(rendered.contains("Choose a directory:"));
        assert!(rendered.contains("Enter to confirm, Esc to cancel"));
    }
}

