// WHY: session id, oldpwd dedup, and prompt-wrapping mirror zoxide's pwsh init.
const TEMPLATE: &str = r#"# furet PowerShell integration, generated by `furet init pwsh`.
# Mirrors zoxide's PowerShell hook: a session-scoped id, an "oldpwd" dedup
# variable shared between the jump function and the prompt hook, and a
# prompt wrapper that preserves any prompt already defined (oh-my-posh etc).

$global:__furet_session = [guid]::NewGuid().ToString()
$global:__furet_last_pwd = (Get-Location).Path

function global:__furet_record($target, $from, $source, $query) {
    if (-not [string]::IsNullOrWhiteSpace($query)) {
        furet add --session $global:__furet_session --source $source --from $from --query $query -- $target | Out-Null
    } else {
        furet add --session $global:__furet_session --source $source --from $from -- $target | Out-Null
    }
    $global:__furet_last_pwd = $target
}

function global:__furet_hook {
    $current = (Get-Location).Path
    if ($current -ne $global:__furet_last_pwd) {
        __furet_record $current $global:__furet_last_pwd 'hook'
    }
}

if (Test-Path Function:\prompt) {
    $global:__furet_prompt_old = $function:prompt
} else {
    $global:__furet_prompt_old = $null
}

function global:prompt {
    __furet_hook
    if ($null -ne $global:__furet_prompt_old) {
        & $global:__furet_prompt_old
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($NestedPromptLevel + 1)) "
    }
}

function global:__FURET_CMD__ {
    param([Alias('l')] [switch] $Local, [Alias('h')] [switch] $HomeScope, [Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $scope = @()
    if ($Local.IsPresent -or ($FuretArgs -contains '--local')) {
        $scope += '--local'
    }
    if ($HomeScope.IsPresent -or ($FuretArgs -contains '--home')) {
        $scope += '--home'
    }
    $scoped = $scope.Count -gt 0
    $FuretArgs = @($FuretArgs | Where-Object { $_ -ne '--local' -and $_ -ne '--home' })

    # WHY: --explain is answered before every other dispatch, so even a bare
    # `f --explain` reports on the pool instead of jumping home.
    if ($FuretArgs -contains '--explain') {
        $query = (($FuretArgs | Where-Object { $_ -ne '--explain' }) -join ' ') -replace '/', '\'
        furet query --explain @scope -- $query
        return
    }

    # WHY: with -l or -h every special form is skipped, so the jump always
    # goes through the scoped query — including its empty-query root.
    if ($scoped) {
        $query = ($FuretArgs -join ' ') -replace '/', '\'
        $from = (Get-Location).Path
        if ([string]::IsNullOrEmpty($query)) {
            $target = furet query @scope
        } else {
            $target = furet query @scope -- $query
        }
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    if ([string]::IsNullOrEmpty($query)) {
        $furetHome = furet home
        if ([string]::IsNullOrEmpty($furetHome)) {
            $furetHome = $HOME
        }
        Set-Location -LiteralPath $furetHome
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    if ($query -eq '.') {
        return
    }

    if ($query -match '^\.\.+$') {
        $levels = $query.Length - 1
        $target = furet up $levels
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'up'
        return
    }

    if ($query -eq '-') {
        $target = furet back --session $global:__furet_session
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'back'
        return
    }

    if ($query -match '^-[0-9]+$') {
        $target = furet back --session $global:__furet_session --steps $query.Substring(1)
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'back'
        return
    }

    if (Test-Path -LiteralPath $query -PathType Container) {
        Set-Location -LiteralPath $query
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    $target = furet query -- $query
    if ($LASTEXITCODE -ne 0) {
        return
    }
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump'
}

function global:fi {
    param([Alias('l')] [switch] $Local, [Alias('h')] [switch] $HomeScope, [Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $scope = @()
    if ($Local.IsPresent -or ($FuretArgs -contains '--local')) {
        $scope += '--local'
    }
    if ($HomeScope.IsPresent -or ($FuretArgs -contains '--home')) {
        $scope += '--home'
    }
    $scoped = $scope.Count -gt 0
    $FuretArgs = @($FuretArgs | Where-Object { $_ -ne '--local' -and $_ -ne '--home' })

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    # WHY: an alias word opens the alias menu, fed by `furet alias complete`, and is never ranked.
    if (-not $scoped -and $FuretArgs.Count -eq 1 -and ($FuretArgs[0].StartsWith('!') -or $FuretArgs[0].StartsWith('='))) {
        $word = $FuretArgs[0]
        $entries = @(furet alias complete -- $word 2>$null)
        if ($entries.Count -eq 0) {
            return
        }
        if (Get-Command fzf -ErrorAction SilentlyContinue) {
            $lines = @($entries | fzf --delimiter "`t" --query $word.Substring(1) --preview "furet preview {2}" --preview-window "right,50%")
            if ($lines.Count -lt 1) {
                return
            }
            $target = ($lines[0] -split "`t", 2)[1]
        } else {
            $candidates = @($entries | Select-Object -First 9)
            Write-Host 'Choose a directory:'
            for ($i = 0; $i -lt $candidates.Count; $i++) {
                $name, $path = $candidates[$i] -split "`t", 2
                Write-Host "  $($i + 1)) $name  $path"
            }
            Write-Host 'Enter to confirm, Esc to cancel'
            $answer = Read-Host
            if ($answer -notmatch '^[1-9][0-9]*$') {
                return
            }
            $index = [int]$answer
            if ($index -lt 1 -or $index -gt $candidates.Count) {
                return
            }
            $target = ($candidates[$index - 1] -split "`t", 2)[1]
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }

    if (Get-Command fzf -ErrorAction SilentlyContinue) {
        # WHY: the print-query flag makes fzf prepend the final query line (empty
        # query included), so lines[0] is the query and lines[1] the selection;
        # under two lines fzf was aborted or selected nothing.
        $initial = furet query --list --color @scope
        $lines = @($initial | fzf --disabled --ansi --print-query --preview "furet preview {}" --preview-window "right,50%" --bind "change:reload:furet query --list --color $($scope -join ' ') {q}")
        if ($lines.Count -lt 2) {
            return
        }
        $finalQuery = $lines[0]
        $selection = $lines[1]
        $target = $selection -replace "`e\[[0-9;]*m", ''
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump' $finalQuery
        return
    }

    $candidates = @(furet query --list @scope $query | Select-Object -First 9)
    if ($candidates.Count -eq 0) {
        return
    }
    Write-Host 'Choose a directory:'
    for ($i = 0; $i -lt $candidates.Count; $i++) {
        Write-Host "  $($i + 1)) $($candidates[$i])"
    }
    Write-Host 'Enter to confirm, Esc to cancel'
    $answer = Read-Host
    if ($answer -notmatch '^[1-9][0-9]*$') {
        return
    }
    $index = [int]$answer
    if ($index -lt 1 -or $index -gt $candidates.Count) {
        return
    }
    $target = $candidates[$index - 1]
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump' $query
}

# WHY: fm has no param() block so that pwsh never binds -d.
function global:fm {
    if ($args.Count -eq 0) {
        furet mark list
        return
    }
    if ($args.Count -eq 1 -and ($args[0] -eq '+' -or $args[0] -eq '-')) {
        $from = (Get-Location).Path
        $target = if ($args[0] -eq '+') { furet mark next } else { furet mark prev }
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }
    if ($args[0] -eq '-d!') {
        furet mark delete --all @($args | Select-Object -Skip 1)
        return
    }
    if ($args[0] -eq '-d') {
        furet mark delete @($args | Select-Object -Skip 1)
        return
    }
    furet mark set @args
}

# WHY: fh has no param() block, like fm, so -a and -n reach furet history untouched.
function global:fh {
    if ($args -contains '-a' -or $args -contains '--all') {
        furet history @args
        return
    }
    furet history --session $global:__furet_session @args
}

# WHY: Ctrl+Alt+arrows because Windows Terminal takes Alt+arrows for pane focus, PSReadLine takes Alt+digits and brackets are impractical on AZERTY; they act only on an empty line, so typed text is never lost.
if (Get-Module PSReadLine) {
    Set-PSReadLineKeyHandler -Chord 'Ctrl+Alt+RightArrow' -BriefDescription FuretNextMark -Description 'furet: jump to the next mark (fm +)' -ScriptBlock {
        param($key, $arg)
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -ne 0) {
            [Microsoft.PowerShell.PSConsoleReadLine]::Ding()
            return
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert('fm +')
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }
    Set-PSReadLineKeyHandler -Chord 'Ctrl+Alt+LeftArrow' -BriefDescription FuretPreviousMark -Description 'furet: jump to the previous mark (fm -)' -ScriptBlock {
        param($key, $arg)
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line.Length -ne 0) {
            [Microsoft.PowerShell.PSConsoleReadLine]::Ding()
            return
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert('fm -')
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }
}

# WHY: a plain <Tab> on the current word cycles through `furet query --list`
# in ranked order; zoxide instead triggers on a trailing space and rewrites
# the whole line, which this completer deliberately does not do. stderr is
# discarded and LASTEXITCODE restored so a Tab press stays side-effect free.
Register-ArgumentCompleter -CommandName __FURET_CMD__ -ParameterName FuretArgs -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

    if (-not ($commandAst -is [System.Management.Automation.Language.CommandAst])) {
        return
    }
    $arguments = $commandAst.CommandElements.Count - 1
    $scope = $null
    $first = if ($commandAst.CommandElements.Count -gt 1) { $commandAst.CommandElements[1].Extent.Text } else { $null }
    if ($first -eq '-l' -or $first -eq '--local') {
        $scope = '--local'
    } elseif ($first -eq '-h' -or $first -eq '--home') {
        $scope = '--home'
    }
    if ($scope) {
        if ($arguments -gt 2 -or ($arguments -eq 2 -and [string]::IsNullOrEmpty($wordToComplete))) {
            return
        }
    } elseif ($arguments -gt 1 -or ($arguments -eq 1 -and [string]::IsNullOrEmpty($wordToComplete))) {
        return
    }
    if ($wordToComplete.StartsWith('-') -or $wordToComplete -match '^\.+$') {
        return
    }

    # WHY: Get-Variable hands back a live PSVariable reference, so the value is
    # snapshotted before furet runs, not read back in the finally block.
    $lastExit = Get-Variable -Name LASTEXITCODE -Scope Global -ErrorAction SilentlyContinue
    if ($null -ne $lastExit) {
        $lastExit = $lastExit.Value
    }
    try {
        # WHY: alias words complete by strict prefix via `furet alias complete`, never the query list.
        if ($wordToComplete.StartsWith('!') -or $wordToComplete.StartsWith('=')) {
            if ($scope) {
                return
            }
            foreach ($line in @(furet alias complete -- $wordToComplete 2>$null)) {
                $name, $path = $line -split "`t", 2
                [System.Management.Automation.CompletionResult]::new($name, "$name  $path", 'ParameterValue', $path)
            }
            return
        }
        $word = $wordToComplete.Replace('/', '\')
        $lines = if ($scope) {
            @(furet query --list $scope -- $word 2>$null)
        } else {
            @(furet query --list -- $word 2>$null)
        }
        foreach ($line in $lines) {
            $completionText = $line
            if ($line -notmatch '^[\w\\/:.\-]+$') {
                $completionText = "'" + $line.Replace("'", "''") + "'"
            }
            [System.Management.Automation.CompletionResult]::new($completionText, $line, 'ParameterValue', $line)
        }
    } finally {
        if ($null -ne $lastExit) {
            $global:LASTEXITCODE = $lastExit
        }
    }
}
"#;

/// Renders the PowerShell integration script for the jump function `cmd`.
pub fn script(cmd: &str) -> String {
    TEMPLATE.replace("__FURET_CMD__", cmd)
}

#[cfg(test)]
mod tests {
    use super::script;

    #[test]
    fn script_names_the_jump_function_after_cmd() {
        let rendered = script("f");
        assert!(rendered.contains("function global:f "));
    }

    #[test]
    fn script_never_bakes_in_a_session_id() {
        let rendered = script("f");
        assert!(rendered.contains("[guid]::NewGuid()"));
        assert!(!rendered.contains("00000000-0000-0000-0000-000000000000"));
    }

    #[test]
    fn script_defines_fi_and_reaches_for_fzf() {
        let rendered = script("f");
        assert!(rendered.contains("function global:fi "));
        assert!(rendered.contains("fzf"));
    }

    #[test]
    fn script_renders_the_spec_section_9_menu_wording_for_the_no_fzf_branch() {
        let rendered = script("f");
        assert!(rendered.contains("Choose a directory:"));
        assert!(rendered.contains("Enter to confirm, Esc to cancel"));
    }

    #[test]
    fn script_registers_a_tab_completer_on_the_jump_function() {
        let rendered = script("f");
        assert!(rendered.contains("Register-ArgumentCompleter"));
        assert!(rendered.contains("-CommandName f"));
    }

    #[test]
    fn script_registers_no_native_completer_for_the_jump_function() {
        let rendered = script("f");
        assert!(!rendered.contains("-Native"));
    }

    #[test]
    fn script_binds_mark_keys_only_on_an_empty_line() {
        let rendered = script("f");
        assert!(rendered.contains("'Ctrl+Alt+RightArrow'"));
        assert!(rendered.contains("'Ctrl+Alt+LeftArrow'"));
        assert!(rendered.contains("Insert('fm +')"));
        assert!(rendered.contains("Insert('fm -')"));
        assert_eq!(rendered.matches("$line.Length -ne 0").count(), 2);
    }

    #[test]
    fn script_fi_opens_the_alias_menu_unscoped() {
        let rendered = script("f");
        assert!(rendered.contains("furet alias complete -- $word"));
        assert!(rendered.contains("furet preview {2}"));
    }

    #[test]
    fn script_defines_fh_whatever_the_cmd() {
        let rendered = script("f");
        assert!(rendered.contains("function global:fh "));
        let renamed = script("j");
        assert!(renamed.contains("function global:fh "));
        assert!(!renamed.contains("function global:jh "));
    }
}
