// WHY: session id, oldpwd dedup, and prompt-wrapping mirror zoxide's pwsh init.
const TEMPLATE: &str = r#"# furet PowerShell integration, generated by `furet init pwsh`.
# Mirrors zoxide's PowerShell hook: a session-scoped id, an "oldpwd" dedup
# variable shared between the jump function and the prompt hook, and a
# prompt wrapper that preserves any prompt already defined (oh-my-posh etc).

$global:__furet_session = [guid]::NewGuid().ToString()
$global:__furet_last_pwd = (Get-Location).Path

function global:__furet_record($target, $from, $source) {
    furet add --session $global:__furet_session --source $source --from $from -- $target | Out-Null
    $global:__furet_last_pwd = $target
}

function global:__furet_hook {
    $current = (Get-Location).Path
    if ($current -ne $global:__furet_last_pwd) {
        __furet_record $current $global:__furet_last_pwd 'hook'
    }
}

if (Test-Path Function:\prompt) {
    $global:__furet_prompt_old = $function:prompt
} else {
    $global:__furet_prompt_old = $null
}

function global:prompt {
    __furet_hook
    if ($null -ne $global:__furet_prompt_old) {
        & $global:__furet_prompt_old
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($NestedPromptLevel + 1)) "
    }
}

function global:__FURET_CMD__ {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $local = ($FuretArgs -contains '-l') -or ($FuretArgs -contains '--local')
    $FuretArgs = @($FuretArgs | Where-Object { $_ -ne '-l' -and $_ -ne '--local' })

    # WHY: --explain is answered before every other dispatch, so even a bare
    # `f --explain` reports on the pool instead of jumping home.
    if ($FuretArgs -contains '--explain') {
        $query = (($FuretArgs | Where-Object { $_ -ne '--explain' }) -join ' ') -replace '/', '\'
        if ($local) {
            furet query --explain --local -- $query
            return
        }
        furet query --explain -- $query
        return
    }

    # WHY: with -l every special form is skipped, so the jump always goes
    # through the project-scoped query — including its empty-query root.
    if ($local) {
        $query = ($FuretArgs -join ' ') -replace '/', '\'
        $from = (Get-Location).Path
        if ([string]::IsNullOrEmpty($query)) {
            $target = furet query --local
        } else {
            $target = furet query --local -- $query
        }
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    if ([string]::IsNullOrEmpty($query)) {
        $furetHome = furet home
        if ([string]::IsNullOrEmpty($furetHome)) {
            $furetHome = $HOME
        }
        Set-Location -LiteralPath $furetHome
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    if ($query -eq '.') {
        return
    }

    if ($query -match '^\.\.+$') {
        $levels = $query.Length - 1
        $target = furet up $levels
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'up'
        return
    }

    if ($query -eq '-') {
        $target = furet back --session $global:__furet_session
        if ($LASTEXITCODE -ne 0) {
            return
        }
        Set-Location -LiteralPath $target
        __furet_record $target $from 'back'
        return
    }

    if (Test-Path -LiteralPath $query -PathType Container) {
        Set-Location -LiteralPath $query
        __furet_record (Get-Location).Path $from 'jump'
        return
    }

    $target = furet query -- $query
    if ($LASTEXITCODE -ne 0) {
        return
    }
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump'
}

function global:fi {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $FuretArgs)

    $local = ($FuretArgs -contains '-l') -or ($FuretArgs -contains '--local')
    $FuretArgs = @($FuretArgs | Where-Object { $_ -ne '-l' -and $_ -ne '--local' })

    $query = ($FuretArgs -join ' ') -replace '/', '\'
    $from = (Get-Location).Path

    if (Get-Command fzf -ErrorAction SilentlyContinue) {
        if ($local) {
            $initial = furet query --list --color --local
            $selection = $initial | fzf --disabled --ansi --bind "change:reload:furet query --list --color --local {q}"
        } else {
            $initial = furet query --list --color
            $selection = $initial | fzf --disabled --ansi --bind "change:reload:furet query --list --color {q}"
        }
        if ([string]::IsNullOrEmpty($selection)) {
            return
        }
        $target = $selection -replace "`e\[[0-9;]*m", ''
        Set-Location -LiteralPath $target
        __furet_record $target $from 'jump'
        return
    }

    if ($local) {
        $candidates = @(furet query --list --local $query | Select-Object -First 9)
    } else {
        $candidates = @(furet query --list $query | Select-Object -First 9)
    }
    if ($candidates.Count -eq 0) {
        return
    }
    Write-Host 'Choose a directory:'
    for ($i = 0; $i -lt $candidates.Count; $i++) {
        Write-Host "  $($i + 1)) $($candidates[$i])"
    }
    Write-Host 'Enter to confirm, Esc to cancel'
    $answer = Read-Host
    if ($answer -notmatch '^[1-9][0-9]*$') {
        return
    }
    $index = [int]$answer
    if ($index -lt 1 -or $index -gt $candidates.Count) {
        return
    }
    $target = $candidates[$index - 1]
    Set-Location -LiteralPath $target
    __furet_record $target $from 'jump'
}

# WHY: a plain <Tab> on the current word cycles through `furet query --list`
# in ranked order; zoxide instead triggers on a trailing space and rewrites
# the whole line, which this completer deliberately does not do. stderr is
# discarded and LASTEXITCODE restored so a Tab press stays side-effect free.
Register-ArgumentCompleter -CommandName __FURET_CMD__ -ParameterName FuretArgs -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

    if (-not ($commandAst -is [System.Management.Automation.Language.CommandAst])) {
        return
    }
    $arguments = $commandAst.CommandElements.Count - 1
    $local = $commandAst.CommandElements.Count -gt 1 -and (
        $commandAst.CommandElements[1].Extent.Text -eq '-l' -or
        $commandAst.CommandElements[1].Extent.Text -eq '--local')
    if ($local) {
        if ($arguments -gt 2 -or ($arguments -eq 2 -and [string]::IsNullOrEmpty($wordToComplete))) {
            return
        }
    } elseif ($arguments -gt 1 -or ($arguments -eq 1 -and [string]::IsNullOrEmpty($wordToComplete))) {
        return
    }
    if ($wordToComplete.StartsWith('-') -or $wordToComplete -match '^\.+$') {
        return
    }

    # WHY: Get-Variable hands back a live PSVariable reference, so the value is
    # snapshotted before furet runs, not read back in the finally block.
    $lastExit = Get-Variable -Name LASTEXITCODE -Scope Global -ErrorAction SilentlyContinue
    if ($null -ne $lastExit) {
        $lastExit = $lastExit.Value
    }
    try {
        $word = $wordToComplete.Replace('/', '\')
        $lines = if ($local) {
            @(furet query --list --local -- $word 2>$null)
        } else {
            @(furet query --list -- $word 2>$null)
        }
        foreach ($line in $lines) {
            $completionText = $line
            if ($line -notmatch '^[\w\\/:.\-]+$') {
                $completionText = "'" + $line.Replace("'", "''") + "'"
            }
            [System.Management.Automation.CompletionResult]::new($completionText, $line, 'ParameterValue', $line)
        }
    } finally {
        if ($null -ne $lastExit) {
            $global:LASTEXITCODE = $lastExit
        }
    }
}

# WHY: a first argument of `-l` defeats pwsh's parameter binding, so the
# regular completer above is never invoked for those lines; pwsh then calls
# this native fallback with the raw line as the "parameter name" and the
# cursor column as the "word", from which the real word is reconstructed.
Register-ArgumentCompleter -CommandName __FURET_CMD__ -Native -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

    $text = ('' + $parameterName).Trim()
    $column = 0
    if (-not [int]::TryParse('' + $wordToComplete, [ref]$column)) {
        return
    }
    $tokens = @($text -split '\s+' | Where-Object { $_ -ne '' })
    if ($tokens.Count -lt 2 -or $tokens[1] -ne '-l') {
        return
    }
    $word = ''
    if ($column -le $text.Length) {
        $prefix = $text.Substring(0, $column)
        $idx = $prefix.LastIndexOf(' ')
        $word = if ($idx -ge 0) { $prefix.Substring($idx + 1) } else { $prefix }
    }
    $arguments = $tokens.Count - 1
    if ($arguments -gt 2 -or ($arguments -eq 2 -and [string]::IsNullOrEmpty($word))) {
        return
    }
    if ($word.StartsWith('-') -or $word -match '^\.+$') {
        return
    }
    $lastExit = Get-Variable -Name LASTEXITCODE -Scope Global -ErrorAction SilentlyContinue
    if ($null -ne $lastExit) {
        $lastExit = $lastExit.Value
    }
    try {
        $word = $word.Replace('/', '\')
        foreach ($line in @(furet query --list --local -- $word 2>$null)) {
            $completionText = $line
            if ($line -notmatch '^[\w\\/:.\-]+$') {
                $completionText = "'" + $line.Replace("'", "''") + "'"
            }
            [System.Management.Automation.CompletionResult]::new($completionText, $line, 'ParameterValue', $line)
        }
    } finally {
        if ($null -ne $lastExit) {
            $global:LASTEXITCODE = $lastExit
        }
    }
}
"#;

/// Renders the PowerShell integration script for the jump function `cmd`.
pub fn script(cmd: &str) -> String {
    TEMPLATE.replace("__FURET_CMD__", cmd)
}

#[cfg(test)]
mod tests {
    use super::script;

    #[test]
    fn script_names_the_jump_function_after_cmd() {
        let rendered = script("f");
        assert!(rendered.contains("function global:f "));
    }

    #[test]
    fn script_never_bakes_in_a_session_id() {
        let rendered = script("f");
        assert!(rendered.contains("[guid]::NewGuid()"));
        assert!(!rendered.contains("00000000-0000-0000-0000-000000000000"));
    }

    #[test]
    fn script_defines_fi_and_reaches_for_fzf() {
        let rendered = script("f");
        assert!(rendered.contains("function global:fi "));
        assert!(rendered.contains("fzf"));
    }

    #[test]
    fn script_renders_the_spec_section_9_menu_wording_for_the_no_fzf_branch() {
        let rendered = script("f");
        assert!(rendered.contains("Choose a directory:"));
        assert!(rendered.contains("Enter to confirm, Esc to cancel"));
    }

    #[test]
    fn script_registers_a_tab_completer_on_the_jump_function() {
        let rendered = script("f");
        assert!(rendered.contains("Register-ArgumentCompleter"));
        assert!(rendered.contains("-CommandName f"));
    }
}
